Repository DenverCoder1/github-readme-streak-stats, pull requests merged in 2022-10, with the labels that each got.

#336 feat: Wrap long lines and allow for two-line translation strings
  src/card.php
  tests/RenderTest.php
  tests/expected/test_border_radius_card.svg
  tests/expected/test_card.svg
  tests/expected/test_date_card.svg
  tests/expected/test_error_card.svg
  tests/expected/test_locale_ja_card.svg
Labels: enhancement

#337 fix: replace wordwrap to support utf8 words
  src/card.php
  src/translations.php
  tests/RenderTest.php
Labels: bug

#334 Added Tamil Translation
  src/translations.php
Labels: enhancement

#346 feat: Added "halloween" streak stats theme
  docs/themes.md
  src/themes.php
Labels: enhancement, new theme
