Repository DenverCoder1/github-readme-streak-stats, pull requests merged in 2022-08, with the labels that each got.

#297 docs: Create docs/faq.md and move themes to docs/themes.md
  README.md
  docs/faq.md
  docs/themes.md
Labels: documentation

#298 fix: Use inkscape to convert svg to png
  Aptfile
  app.json
  src/card.php
Labels: bug

#302 feat(demo): add the FAQ link to the demo site
  src/demo/css/style.css
  src/demo/index.php
Labels: enhancement

#304 feat: add python-dark theme
  docs/themes.md
  src/themes.php
Labels: new theme

#314 docs(FAQ): Add git push step in FAQ entry
  docs/faq.md
Labels: documentation
