Repository DenverCoder1/github-readme-streak-stats, pull requests merged in 2022-12, with the labels that each got.

#362 feat: Add weekly contribution mode
  README.md
  src/card.php
  src/demo/index.php
  src/demo/js/script.js
  src/demo/preview.php
  src/index.php
  src/stats.php
  src/translations.php
  tests/RenderTest.php
  tests/StatsTest.php
  tests/TranslationsTest.php
  tests/expected/test_stats.json
Labels: enhancement

#364 fix: Skip graphs if contribution graph returns null
  src/stats.php
Labels: enhancement

#366 docs(readme): Add Issue 32 link in themes
  README.md
Labels: documentation

#367 ci: Fix translation-progress.yml committing extra files
  .github/workflows/translation-progress.yml
  .gitignore
  DOCKER_ENV
  docker_tag
Labels: bug

#368 docs(readme): Add links to line numbers for locales
  scripts/translation-progress.php
Labels: documentation

#369 docs(readme): Fix typos, add comment about locales script
  README.md
Labels: documentation

#371 feat: Added translations for Arabic, Bangla, Hindi, Spanish
  src/translations.php
Labels: enhancement

#370 fix: Solve issue with missing years by retrying
  src/stats.php
Labels: bug

#378 fix: Parse error when user passed contains quotes
  .gitignore
  src/index.php
  src/stats.php
Labels: bug

#380 fix: API error not passing message
  src/demo/preview.php
  src/index.php
  src/stats.php
Labels: bug

#381 feat: Improved Brazilian Portuguese translations
  src/translations.php
Labels: enhancement

#382 feat: Added Persian (fa) translations
  src/translations.php
Labels: enhancement

#383 feat: Added Traditional Chinese translation
  src/translations.php
Labels: enhancement

#385 feat: Added Marathi and corrected Hindi translation
  src/translations.php
Labels: enhancement

#386 docs(readme): Use HTML syntax for locale table
  composer.lock
  scripts/translation-progress.php
Labels: documentation

#387 feat: Added locale aliases and normalization
  README.md
  scripts/translation-progress.php
  src/card.php
  src/demo/index.php
  src/translations.php
  tests/TranslationsTest.php
Labels: enhancement

#388 feat: Added transparent to valid CSS colors list
  src/colors.php
Labels: enhancement

#391 docs(readme): Added steps for deploying to Vercel
  README.md
Labels: documentation

#393 docs(readme): Update vercel instructions with Git note and env image
  README.md
Labels: documentation

#394 refactor: Convert to PNG without using files
  src/card.php
Labels: refactor

#395 docs(readme): Update Vercel information
  README.md
Labels: documentation

#397 fix: Fixed Arabic translations
  src/translations.php
Labels: enhancement
