Repository DenverCoder1/github-readme-streak-stats, pull requests merged in 2023-02, with the labels that each got.

#449 fix: filter years before account creation
  src/stats.php
Labels: bug

#452 feat: Add `disable_animations` parameter
  README.md
  src/card.php
  src/demo/index.php
  src/demo/js/script.js
  tests/RenderTest.php
Labels: enhancement

#462 feat: Add "transparent" theme
  docs/themes.md
  src/themes.php
Labels: new theme

#459 feat: Added rising-sun theme
  docs/themes.md
  src/themes.php
Labels: new theme

#463 feat: Added 18 more themes
  docs/themes.md
  src/themes.php
Labels: new theme

#464 refactor: Normalize theme names and colors
  docs/themes.md
  src/card.php
  src/themes.php
  tests/OptionsTest.php
Labels: refactor

#467 docs(themes): Added info about normalized theme names
  docs/themes.md
Labels: documentation
