Repository DenverCoder1/github-readme-streak-stats, pull requests merged in 2023-01, with the labels that each got.

#401 fix: Only decode json if it's a string
  src/stats.php
Labels: bug

#402 fix: Handle curl errors for single graphQL
  src/stats.php
Labels: bug

#403 fix: Don't retry if rate limit exceeded
  src/stats.php
Labels: bug

#406 fix: Prevent reusing tokens when rate limited
  src/stats.php
Labels: bug

#409 perf: Combine first two requests and refactor
  src/stats.php
Labels: refactor

#410 refactor: Update types and docstrings
  src/card.php
  src/stats.php
Labels: refactor

#427 docs(readme): Clarify date format default value and Locale usage
  README.md
Labels: documentation

#441 feat: Added Haitian Creole translations
  src/translations.php
Labels: enhancement

#443 refactor: Consistent ID naming, redundant return, styling
  src/demo/css/style.css
  src/demo/index.php
  src/demo/js/script.js
Labels: refactor
